# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f547ff48522fe2fa13a6fe2b3a306faeabf4e11ab0a6ae8f4bb0d25559b9b0d91b26c72b49ff1865fda173c760620b7f41e2c1c5668bc8c98b6a41540a4fda93

test:
  secret_key_base: dc4cc99f365f769961332ea0af0b129d8cda62157c31b2dcf8b6d4dbe30fdf846c5a50e9c4287adef577d5b7dc515f18cfe28b14d2e5e9f1b2796d5c219e8133

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
